export type MembershipTier = 'brons' | 'silver' | 'guld' | 'platinum';

export interface Membership {
  id: MembershipTier;
  name: string;
  price: number;
  period: string;
  description: string;
  features: string[];
  popular?: boolean;
}

export interface ClassSession {
  id: string;
  title: string;
  instructor: string;
  day: string;
  startTime: string;
  endTime: string;
  level: 'Nybörjare' | 'Fortsättning' | 'Avancerad' | 'Alla nivåer';
  spots: number;
  spotsLeft: number;
  location: string;
  description: string;
  tags: string[];
  bookable?: boolean;
}

export interface OpeningHours {
  day: string;
  hours: string;
  closed?: boolean;
}

export const memberships: Membership[] = [
  {
    id: 'brons',
    name: 'Brons',
    price: 399,
    period: 'per månad',
    description: 'Fri tillgång till hallen och World Chase Tag-quaden.',
    features: [
      'Fritt inträde till Parkourhall1 under öppettider',
      'Fritt tillträde till World Chase Tag-quaden',
      '10% rabatt på allt i shoppen',
      'Tillgång till gratis community-tillfällen',
    ],
  },
  {
    id: 'silver',
    name: 'Silver',
    price: 599,
    period: 'per månad',
    description: 'Allt i Brons plus en ledarledd klass i veckan.',
    features: [
      'Allt i Brons plus...',
      '1 ledarledd klass i veckan (bokas inför varje tillfälle)',
    ],
  },
  {
    id: 'guld',
    name: 'Guld',
    price: 799,
    period: 'per månad',
    description: 'Bäst värde för pengarna.',
    features: [
      'Allt i Silver plus...',
      '+1 klass (tot. 2 ledarledda klasser/vecka)',
      'Specialist Workshop 1 gång per månad',
      'Ta med en kompis till halva priset',
    ],
    popular: true,
  },
  {
    id: 'platinum',
    name: 'Platinum',
    price: 1199,
    period: 'per månad',
    description: 'Maximal tillgång med alla förmåner.',
    features: [
      'Allt i Guld plus...',
      'Tillgång till alla (tot. 3) Quality Movements klasser/vecka',
      'Välkomst Goodie Bag m. träningströja & klistermärken (värde ca 500kr)',
    ],
  },
];

export const classes: ClassSession[] = [
  // --- MÅNDAG ---
  {
    id: 'cls-man-ph1-6-8',
    title: 'Parkour 6–8år',
    instructor: 'Piam A',
    day: 'Måndag',
    startTime: '16:00',
    endTime: '17:00',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 6–8 år, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-man-ph1-tonar',
    title: 'Parkour Tonårs',
    instructor: 'Piam A',
    day: 'Måndag',
    startTime: '17:10',
    endTime: '18:10',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för tonåringar, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'ungdom'],
  },
  {
    id: 'cls-man-ph1-9-12-forts',
    title: 'Parkour 9–12år Fortsättning',
    instructor: 'Piam A',
    day: 'Måndag',
    startTime: '18:20',
    endTime: '19:20',
    level: 'Fortsättning',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, fortsättningsnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-man-wct-9-12',
    title: 'World Chase Tag 9–12år',
    instructor: 'Mattias H',
    day: 'Måndag',
    startTime: '16:00',
    endTime: '17:00',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'World Chase Tag-träning för barn 9–12 år, nybörjarnivå.',
    tags: ['chase tag', 'barn'],
  },
  {
    id: 'cls-man-wct-13-17',
    title: 'World Chase Tag 13–17år',
    instructor: 'Mattias H',
    day: 'Måndag',
    startTime: '17:10',
    endTime: '18:10',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'World Chase Tag-träning för ungdomar 13–17 år, nybörjarnivå.',
    tags: ['chase tag', 'ungdom'],
  },
  {
    id: 'cls-man-wct-9-17-forts',
    title: 'World Chase Tag 9–17år Fortsättning',
    instructor: 'Mattias H',
    day: 'Måndag',
    startTime: '18:20',
    endTime: '19:20',
    level: 'Fortsättning',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'World Chase Tag-träning för ungdomar 9–17 år, fortsättningsnivå.',
    tags: ['chase tag', 'ungdom'],
  },
  // --- TISDAG ---
  {
    id: 'cls-tis-senior',
    title: 'Parkour Senior',
    instructor: 'Brandon S',
    day: 'Tisdag',
    startTime: '15:00',
    endTime: '16:00',
    level: 'Alla nivåer',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Ledarledd parkourträning för seniorer 55 år och äldre. Ingår som bokningsbar klass i Silver/Guld/Platinum-medlemskap.',
    tags: ['senior', 'parkour'],
    bookable: true,
  },
  {
    id: 'cls-tis-akrobatik-9-12',
    title: 'Akrobatik 9–12år',
    instructor: 'Brandon S',
    day: 'Tisdag',
    startTime: '16:00',
    endTime: '17:00',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Akrobatikträning för barn 9–12 år. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['akrobatik', 'barn'],
  },
  {
    id: 'cls-tis-ph1-9-12-forts',
    title: 'Parkour 9–12år Fortsättning',
    instructor: 'Brandon S',
    day: 'Tisdag',
    startTime: '17:10',
    endTime: '18:10',
    level: 'Fortsättning',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, fortsättningsnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-tis-ph1-9-12-avancerad',
    title: 'Parkour 9–12år Avancerad',
    instructor: 'Brandon S',
    day: 'Tisdag',
    startTime: '18:20',
    endTime: '19:20',
    level: 'Avancerad',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, avancerad nivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-tis-alla-18plus',
    title: 'Parkour 18år+',
    instructor: 'Brandon S',
    day: 'Tisdag',
    startTime: '19:30',
    endTime: '20:30',
    level: 'Alla nivåer',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Ledarledd parkourträning för alla nivåer, 18 år och äldre. Ingår som bokningsbar klass i Silver/Guld/Platinum-medlemskap.',
    tags: ['parkour', 'alla nivåer'],
    bookable: true,
  },
  // --- ONSDAG ---
  {
    id: 'cls-ons-ph1-6-8',
    title: 'Parkour 6–8år',
    instructor: 'Mattias H',
    day: 'Onsdag',
    startTime: '16:00',
    endTime: '17:00',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 6–8 år, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-ons-ph1-9-12-nybörjare',
    title: 'Parkour 9–12år Nybörjare',
    instructor: 'Mattias H',
    day: 'Onsdag',
    startTime: '17:10',
    endTime: '18:10',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-ons-ph1-9-12-forts',
    title: 'Parkour 9–12år Fortsättning',
    instructor: 'Mattias H',
    day: 'Onsdag',
    startTime: '18:20',
    endTime: '19:20',
    level: 'Fortsättning',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, fortsättningsnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-ons-ph1-9-12-avancerad',
    title: 'Parkour 9–12år Avancerad',
    instructor: 'Mattias H',
    day: 'Onsdag',
    startTime: '19:30',
    endTime: '20:30',
    level: 'Avancerad',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, avancerad nivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-onsdag-nacka',
    title: 'Parkour: Alla Nivåer – Nacka',
    instructor: 'Brandon Sandén',
    day: 'Onsdag',
    startTime: '18:30',
    endTime: '20:00',
    level: 'Alla nivåer',
    spots: 12,
    spotsLeft: 12,
    location: 'Varierar varje vecka (Nacka)',
    description: 'Ledarledd parkourträning ute i Nacka för alla nivåer, 13 år och äldre. Samlingsplats varierar varje vecka.',
    tags: ['parkour', 'nacka', 'utomhus'],
    bookable: true,
  },
  // --- TORSDAG ---
  {
    id: 'cls-tor-ph1-9-12-nybörjare',
    title: 'Parkour 9–12år Nybörjare',
    instructor: 'Viktor A',
    day: 'Torsdag',
    startTime: '16:00',
    endTime: '17:00',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-tor-ph1-9-12-forts',
    title: 'Parkour 9–12år Fortsättning',
    instructor: 'Viktor A',
    day: 'Torsdag',
    startTime: '17:10',
    endTime: '18:10',
    level: 'Fortsättning',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, fortsättningsnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-tor-wct-tavling',
    title: 'World Chase Tag 9–17år Tävlingsgrupp',
    instructor: 'Viktor A',
    day: 'Torsdag',
    startTime: '18:30',
    endTime: '19:30',
    level: 'Avancerad',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'World Chase Tag-träning för tävlingsgruppen, 9–17 år.',
    tags: ['chase tag', 'tävling', 'ungdom'],
  },
  // --- LÖRDAG ---
  {
    id: 'cls-lor-ph1-9-12-nybörjare',
    title: 'Parkour 9–12år Nybörjare',
    instructor: 'Melwin H',
    day: 'Lördag',
    startTime: '12:20',
    endTime: '13:20',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-lor-ph1-6-8-nybörjare',
    title: 'Parkour 6–8år Nybörjare',
    instructor: 'Melwin H',
    day: 'Lördag',
    startTime: '13:30',
    endTime: '14:30',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 6–8 år, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  // --- FREDAG ---
  {
    id: 'cls-fre-ph1-9-12-nybörjare',
    title: 'Parkour 9–12år Nybörjare',
    instructor: 'Alfred L',
    day: 'Fredag',
    startTime: '16:00',
    endTime: '17:00',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-fre-ph1-6-8',
    title: 'Parkour 6–8år',
    instructor: 'Alfred L',
    day: 'Fredag',
    startTime: '17:10',
    endTime: '18:10',
    level: 'Nybörjare',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 6–8 år, nybörjarnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-fre-ph1-9-12-avancerad',
    title: 'Parkour 9–12år Avancerad',
    instructor: 'Alfred L',
    day: 'Fredag',
    startTime: '18:20',
    endTime: '19:20',
    level: 'Avancerad',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för barn 9–12 år, avancerad nivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'barn'],
  },
  {
    id: 'cls-fre-ph1-tonar-forts',
    title: 'Parkour Tonårs Fortsättning',
    instructor: 'Alfred L',
    day: 'Fredag',
    startTime: '19:30',
    endTime: '20:30',
    level: 'Fortsättning',
    spots: 12,
    spotsLeft: 12,
    location: 'Parkourhall1, Järfälla',
    description: 'Parkourträning för tonåringar, fortsättningsnivå. Klassen har förtur till utrymmet men övriga medlemmar kan träna i hallen.',
    tags: ['parkour', 'ungdom'],
  },
];

export const openingHours: OpeningHours[] = [
  { day: 'Måndag', hours: '15:00 – 21:00' },
  { day: 'Tisdag', hours: '15:00 – 21:00' },
  { day: 'Onsdag', hours: '15:00 – 21:00' },
  { day: 'Torsdag', hours: '15:00 – 21:00' },
  { day: 'Fredag', hours: '15:00 – 21:00' },
  { day: 'Lördag', hours: '12:00 – 18:00' },
  { day: 'Söndag', hours: '', closed: true },
];

export const DAYS_ORDER = ['Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag', 'Söndag'];
